Detect if this is a merge or rebase in rebase_migration command
adamchainz/django-linear-migrations pull request #260
Opened 2023-05-23 11:37 UTC by dmitrysleptsov

Resolve https://github.com/adamchainz/django-linear-migrations/issues/80. Adds logic to check if there is a merge request in progress. If so, handle it by swapping the migration files.

2023-05-25 20:39 UTC, adamchainz commented
I don't think this is the right approach. It would be better to fix django-linear-migrations to handle both cases. It's possible to detect if the current directory is a Git repository and whether there's a rebase or merge in progress with a few Git commands.

2023-05-26 07:09 UTC, dmitrysleptsov commented
Agree, it's not the fix for the command, it's just the less risky change that allows us to modify the command. I thought it would be simpler to add changes that don't change the logic. But I can make the existing command work with both rebase and merge. I think we can check the existence of the MERGE_HEAD file in the .git directory (in the same way as the [git client does it](https://github.com/libgit2/libgit2/blob/main/src/libgit2/repository.c#L3622). 

The question for me is how far the library should go to find out the path to the .git directory?
1. We could execute something like `git rev-parse --git-dir` directly in the script to find out the path to the .git directory. But in this case we rely on the existence of `git` command.
2. We could ask the user to do it via some setting. Because I'm not sure that setting.BASE_DIR is reliable enough to use it.
And in this case, there is also a question about what we should do if there is no Git repository?

2023-05-26 08:21 UTC, adamchainz commented
Option 2: use `git rev-parse --git-dir`. Ensure it does not crash if `git` is not available. Don't error if there is no Git repository, carry on with the existing presume-rebase behaviour.

2023-05-26 19:42 UTC, dmitrysleptsov commented on src/django_linear_migrations/management/commands/rebase_migration.py
> +        # Either `git` is not available or there is no git repository
If some error should be shown to user, this function can be moved under `Command` class

2023-05-26 19:44 UTC, dmitrysleptsov commented
It's ready for review when you have time @adamchainz . I tested it, works as expected for both `rebase` and `merge`

2023-05-28 05:46 UTC, adamchainz commented
Great, thanks 👍. Can you update the docs to mention the automatic detection , and add a changelog note? I’ll properly review a bit later, if you can do those tasks it would help.

2023-05-29 22:18 UTC, adamchainz requested changes
a few changes I'm going to make

2023-05-29 22:18 UTC, adamchainz commented on CHANGELOG.rst
> +* Improve `rebase_migration` command to handle both rebasing and merging of the base branch
reStructuredText uses two backticks for code

2023-05-29 22:18 UTC, adamchainz commented on CHANGELOG.rst
> +------------------
headers are inserted at release time... I should add a comment to this file to clarify that.

2023-05-29 22:18 UTC, adamchainz commented on tests/test_rebase_migration.py
> +        self.addCleanup(subprocess_run_patch.stop)
I'm gonna rewrite these tests to not use mocking

2023-05-29 22:18 UTC, adamchainz commented on src/django_linear_migrations/management/commands/rebase_migration.py
> +    return Path(git_dir).joinpath("MERGE_HEAD").exists()
we can do better with `git rev-parse --verify MERGE_HEAD`, skipping getting the git dir and reading the internal files

2023-05-29 22:26 UTC, adamchainz commented
I think your pull request did not allow me to push changes, so I have had to create a new one in #261.

For future ref, please ensure the box is checked: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

2023-05-29 23:04 UTC, closed without merging